name: Runner OS Test

on:
  workflow_dispatch:
    

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: System information
        run: |
          echo "OS: Linux"
          echo "Hostname: $(hostname)"
          echo "User: $(whoami)"

  windows:
    runs-on: windows-latest

    steps:
      - name: System information
        shell: pwsh
        run: |
          Write-Host "OS: Windows"
          Write-Host "Hostname: $env:COMPUTERNAME"
          Write-Host "User: $env:USERNAME"

  macos:
    runs-on: macos-latest

    steps:
      - name: System information
        run: |
          echo "OS: macOS"
          echo "Hostname: $(hostname)"
          echo "User: $(whoami)"
